# Generated by Django 5.2.2 on 2025-06-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('beginner', 'Новичок'), ('active', 'Активный'), ('experienced', 'Опытный'), ('oldtimer', 'Ветеран'), ('legend', 'Легенда')], default='beginner', max_length=15)),
                ('feedbacks', models.ManyToManyField(through='user.FeedBack', through_fields=('user', 'author'), to='user.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_feedbacks', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to='user.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('author', 'user')},
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
