# Generated by Django 5.2.2 on 2025-06-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='spot.spot'),
        ),
    ]
